# Generated by Django 4.1.5 on 2023-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receivers_name', models.CharField(max_length=30)),
                ('Receivers_phone_no', models.IntegerField()),
                ('Insta_username', models.CharField(max_length=30)),
                ('Insta_password', models.CharField(max_length=30)),
                ('Insta_receiver', models.CharField(max_length=30)),
            ],
        ),
    ]
