# Generated by Django 4.1.5 on 2023-01-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Receivers_phone_no',
            field=models.IntegerField(),
        ),
    ]
